name = "GeometricTools"
uuid = "83792f5e-c6a1-11e8-2e0a-93511f02ae5f"
authors = ["Eduardo J. Alvarez <Edo.AlvarezR@gmail.com>"]
version = "2.2.1"

[deps]
FLOWMath = "6cb5d3fb-0fe8-4cc2-bd89-9fe0b19a99d3"
Dierckx = "39dd38d3-220a-591b-8e3c-4c3a8c710a94"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
Roots = "f2b01f46-fcfa-551c-844a-d8ac1e96c665"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
PyPlot = "d330b81b-6aea-500a-939a-2ce795aea3ee"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Meshes = "eacbb407-ea5a-433e-ab97-5258b1ca43fa"

[compat]
julia = "1"
FLOWMath = "0.3"
Dierckx = "0.5"
PyCall = "1.94"
QuadGK = "2"
Requires = "1"
Roots = "2"
Statistics = "1"
HDF5 = "0.16"
PyPlot = "2"
Meshes = "0.28 - 0.42"
